/**
 * Contracts for the platform layer — the vendor's own staff, who sit above the
 * tenant model and create customer companies.
 *
 * Kept in a separate module from ./auth so nothing can accidentally treat a
 * platform session as a tenant session. They are different tables, different
 * logins and different token scopes; the type system should say so too.
 */

export type PlatformUserStatus = 'ACTIVE' | 'DISABLED';

/**
 * The signed-in platform operator. Note there is no tenant and no role: a
 * platform user belongs to no company, and every platform user has the same
 * (total) authority. If that ever needs subdividing, it becomes a role column
 * here rather than a reuse of UserRole.
 */
export interface PlatformSessionUser {
  id: string;
  email: string;
  fullName: string;
  status: PlatformUserStatus;
  mustChangePassword: boolean;
}

export interface PlatformLoginResponse {
  user: PlatformSessionUser;
  accessToken: string;
  expiresInSeconds: number;
}

/**
 * Token scope. Present in every access token so a tenant token can never be
 * replayed against a platform route, or the reverse.
 *
 * Without it the two guards would still reject each other's tokens — a platform
 * subject is not in `users`, so the lookup fails — but only by accident of the
 * lookup missing. An explicit scope makes the refusal deliberate and the error
 * message honest.
 */
export type TokenScope = 'tenant' | 'platform';

// ---------------------------------------------------------------------------
// Creating a company
// ---------------------------------------------------------------------------

/**
 * Body of `POST /api/v1/platform/companies`.
 *
 * One request creates both the company and its first Admin, because a company
 * with no Admin is unreachable: nobody can sign in to it and nobody can invite
 * anyone. Splitting them into two calls would allow that state to exist.
 */
export interface CreateCompanyRequest {
  /** Registered company name, e.g. "ABC Pharma". */
  companyName: string;
  /** URL-safe identifier, unique across the platform. Derived from the name if omitted. */
  slug?: string;
  drugLicenceNumber?: string;
  gstin?: string;
  timezone?: string;

  /** The first Admin. They will belong to this company and no other. */
  adminEmail: string;
  adminFullName: string;
  /**
   * Temporary password for that Admin. Generated by the caller so it can be
   * shown once and never stored in readable form.
   */
  adminTemporaryPassword: string;
}

export interface CreateCompanyResponse {
  tenantId: string;
  tenantSlug: string;
  tenantName: string;
  adminUserId: string;
  adminEmail: string;
}

/** A row in the platform's company list. */
export interface CompanyListItem {
  id: string;
  name: string;
  slug: string;
  status: 'TRIAL' | 'ACTIVE' | 'SUSPENDED';
  drugLicenceNumber: string | null;
  gstin: string | null;
  timezone: string;
  /** Counts across the whole company, which only the platform can see. */
  userCount: number;
  adminCount: number;
  activeUserCount: number;
  createdAt: string;
  /** Most recent sign-in by anyone at the company; null if nobody ever has. */
  lastActivityAt: string | null;
}

/** Body of `PATCH /api/v1/platform/companies/:id`. */
export interface UpdateCompanyRequest {
  name?: string;
  drugLicenceNumber?: string;
  gstin?: string;
  timezone?: string;
  /**
   * SUSPENDED blocks every sign-in for that company immediately — the auth
   * guard re-reads tenant status on each request.
   */
  status?: 'TRIAL' | 'ACTIVE' | 'SUSPENDED';
}

// ---------------------------------------------------------------------------
// Platform dashboard
// ---------------------------------------------------------------------------

/** System-wide figures, visible only to platform staff. */
export interface PlatformDashboard {
  companies: {
    total: number;
    trial: number;
    active: number;
    suspended: number;
  };
  users: {
    /** Every tenant user across every company. */
    total: number;
    admins: number;
    active: number;
    /** Created but never signed in, or holding an admin-set password. */
    pending: number;
    disabled: number;
  };
  /** Platform operators, not tenant users. */
  platformUsers: {
    total: number;
    active: number;
  };
  activity: {
    signInsLast24h: number;
    companiesCreatedLast30d: number;
    /** Newest first. */
    recent: PlatformActivityItem[];
  };
  health: {
    databaseStatus: 'up' | 'down';
    databaseLatencyMs: number | null;
    /** Total rows in the tenant audit trail — a rough activity measure. */
    auditRecordCount: number;
  };
}

export interface PlatformActivityItem {
  action: string;
  entityType: string;
  entityId: string | null;
  actor: string | null;
  at: string;
}

/** Route paths for the platform console, shared with the web middleware. */
export const PLATFORM_ROUTES = {
  login: '/platform/login',
  dashboard: '/platform',
  companies: '/platform/companies',
  changePassword: '/platform/change-password',
  afterLogout: '/platform/login',
} as const;

/**
 * Cookie holding the platform access token. Deliberately a different name from
 * the tenant cookie so both sessions can coexist in one browser — a Super User
 * demonstrating a customer's account should not sign themselves out.
 */
export const PLATFORM_SESSION_COOKIE_NAME = 'pharma_erp_platform_session';
